Listen for keydown events to change direction of the car. #1
allen-huang9/driving-game pull request #7
Opened 2020-11-05 23:11 UTC by allen-huang9

![car-turning](https://user-images.githubusercontent.com/8008839/98306690-278d2f00-1f79-11eb-9a44-95384000c273.gif)

2020-11-05 23:14 UTC, codingcodymiller requested changes

2020-11-05 23:14 UTC, codingcodymiller commented on main.js
> +    $car.setAttribute('style', ' width: 100px; transform-origin: center; transform: rotate(' +
Instead of doing all this as inline styling, you should make CSS classes for the car, and each direction :+1:

2020-11-06 00:34 UTC, uzair-ashraf requested changes
You also need a data model.
![image](https://user-images.githubusercontent.com/52118958/98311661-c4a19500-1f84-11eb-9600-d6b824c64458.png)

2020-11-06 00:34 UTC, uzair-ashraf commented on main.js
> +  }
This logic seems to be difficult and hard to read.  Less code is often not as good as readable code.

You can use words like up down left and right to dictate what direction the car should go.

2020-11-06 00:34 UTC, uzair-ashraf commented on styles.css
> +}
If you want the car to move in 8 directions that is fine, however you only need four.

Numbers are harder to read, so feel free to use things like `.direction.top-right` and `direction.top-left`

Again, 4 directions would be much better for MVP.

2020-11-06 01:06 UTC, uzair-ashraf requested changes
Its a bit better, still very hard to read, with numbers instead of direction. However it is acceptable.

Still needs a data model though.

![image](https://user-images.githubusercontent.com/52118958/98313666-31b72980-1f89-11eb-9774-54d423cdf443.png)

2020-11-06 01:30 UTC, uzair-ashraf approved these changes

2020-11-06 01:31 UTC, merged